# Обработка ошибок

Время, мин: 15
Дата изучения: March 24, 2023
Изучено: Yes
Содержание: try{ } catch (error) { } 
Тип занятия: Лекция

```jsx
try {
	// Выполнение блока кода
} catch (error) {
	// Этот блок выполняется в случае возникновения ошибок в блоке try
} 
```

из блока **catch** → мы можем иметь доступ к переменной **error**, которая появилась в **блоке try** и совершать с ней действия 

то есть **значение ошибки** в **блоке try** будет **присвоено переменной** в качестве параметра функции catch

```jsx
const fnWithError = () => {
	throw new Error('Some error')
}

try {
	fnWithError ()
} catch (error) {
	console.error(error); // метод для лучшего вывода ошибки в консоль в браузере
	console.log(error.message) // сообщение ошибки
}

console.log('Continue...')
```